src/objects/Ludus_Point__c.object
<CustomObject>
    <fields>
        <fullName>Origin_Type__c</fullName>
        <label>Origin Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ludus Rule</label>
        <referenceTo>Ludus_Rule__c</referenceTo>
        <relationshipLabel>Ludus Points</relationshipLabel>
        <relationshipName>Ludus_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ludus_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ludus Point</label>
    <nameField>
        <label>Ludus Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ludus Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PushTopicManager.cls
public with sharing class PushTopicManager {
    public static void createUpdateCasePushTopic(){
        PushTopic pushTopic = new PushTopic();
        pushTopic.Name = 'CaseUpdates';
        pushTopic.Query = 'SELECT Id, CaseNumber, Subject, Status FROM Case';
        pushTopic.ApiVersion = 38.0;
        pushTopic.NotifyForOperationCreate = true;
        pushTopic.NotifyForOperationUpdate = true;
        pushTopic.NotifyForOperationUndelete = true;
        pushTopic.NotifyForOperationDelete = true;
        pushTopic.NotifyForFields = 'Referenced';
        insert pushTopic;
    }

    public static void pointsPushTopic(){
        PushTopic pushTopic = new PushTopic();
        pushTopic.Name = 'PointUpdates';
        pushTopic.Query = 'SELECT Id,Name,Origin_Type__c,Origin__c,Points__c,Rule__c,User__c FROM Ludus_Point__c';
        pushTopic.ApiVersion = 38.0;
        pushTopic.NotifyForOperationCreate = true;
        pushTopic.NotifyForOperationUpdate = true;
        pushTopic.NotifyForOperationUndelete = true;
        pushTopic.NotifyForOperationDelete = true;
        pushTopic.NotifyForFields = 'Referenced';
        insert pushTopic;
    }
}