src/objects/Ludus_Point__c.object
<CustomObject>
    <fields>
        <fullName>Compound_Key__c</fullName>
        <externalId>true</externalId>
        <label>Compound Key</label>
        <length>37</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin_Type__c</fullName>
        <label>Origin Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ludus Rule</label>
        <referenceTo>Ludus_Rule__c</referenceTo>
        <relationshipLabel>Ludus Points</relationshipLabel>
        <relationshipName>Ludus_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ludus_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ludus Point</label>
    <nameField>
        <label>Ludus Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ludus Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ludus_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Compare_Date_Field__c</fullName>
        <label>Compare Date Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compare_Date_Value__c</fullName>
        <label>Compare Date Value</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Compare_Field_Value__c</fullName>
        <label>Compare Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compare_Numeric_Field__c</fullName>
        <label>Compare Numeric Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compare_Numeric_Value__c</fullName>
        <label>Compare Numeric Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals</fullName>
                    <default>true</default>
                    <label>Equals</label>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Rule__c</fullName>
        <label>Type of Rule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Picklist</fullName>
                    <default>true</default>
                    <label>Picklist</label>
                </value>
                <value>
                    <fullName>Numeric</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Awarded__c</fullName>
        <label>User Awarded</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ludus Rule</label>
    <nameField>
        <label>Ludus Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ludus Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GamificationEngine.cls
/**
 * Created by miguel.mota on 9/19/18.
 */

public with sharing class GamificationEngine {

    private static List<Ludus_Point__c> points = new List<Ludus_Point__c>();

    public static void handleCRUD(String objectName, Map<Id, sObject> newObjects, Map<Id, sObject> oldObjects){
        system.debug('ja foste');
        List<Ludus_Rule__c> rules = [SELECT Compare_Date_Field__c,Compare_Date_Value__c,Compare_Field_Value__c,
                                            Compare_Numeric_Field__c,Compare_Numeric_Value__c,Field__c,Id,
                                            Object__c,Operator__c,Points__c,Type_of_Rule__c,User_Awarded__c
                                        FROM Ludus_Rule__c
                                        WHERE Object__c = :objectName];

        for(Ludus_Rule__c rule : rules) {
            for(String key : newObjects.keySet()){
                checkRuleOnObject(rule, newObjects.get(key), oldObjects.get(key));
            }
        }

        if(!points.isEmpty()) Database.upsert(points, Ludus_Point__c.Compound_Key__c);
    }


    private static void checkRuleOnObject(Ludus_Rule__c rule, sObject newSObject, sObject oldSObject) {
        if(rule.Type_of_Rule__c == 'Picklist') {
            String field = rule.Field__c;
            String target = rule.Compare_Field_Value__c;
            String userAwarded = rule.User_Awarded__c;

            String oldValue = String.valueOf(oldSObject.get(field));
            String newValue = String.valueOf(newSObject.get(field));
            String objectId = String.valueOf(newSObject.get('Id'));
            String userId = String.valueOf(newSObject.get(userAwarded));

            if(oldValue != newValue && newValue == target) {
                awardPoints(rule, objectId, userId);
            }

        } else if(rule.Type_of_Rule__c == 'Numeric') {

        } else if(rule.Type_of_Rule__c == 'Date') {

        }
    }

    private static void awardPoints(Ludus_Rule__c rule, String originId, String userId){
        Ludus_Point__c point = new Ludus_Point__c();
        point.Origin__c = originId;
        point.Origin_Type__c = rule.Object__c;
        point.Rule__c = rule.Id;
        point.User__c = userId;
        point.Points__c = rule.Points__c;
        point.Compound_Key__c = rule.Id + '|' + originId;
        points.add(point);
    }

}