src/objects/Ludus_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals</fullName>
                    <default>true</default>
                    <label>Equals</label>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Rule__c</fullName>
        <label>Type of Rule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Picklist</fullName>
                    <default>true</default>
                    <label>Picklist</label>
                </value>
                <value>
                    <fullName>Numeric</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ludus Rule</label>
    <nameField>
        <label>Ludus Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ludus Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RuleEditorController.cls
public class RuleEditorController extends BaseController {
    @AuraEnabled
    public static Map<String,String> fetchAvailableObjects() {
        return RuleEditorHelper.getTriggableObjects();
    }

    @AuraEnabled
    public static Map<String,String> fetchObjectPicklists(String objectName) {
        return RuleEditorHelper.getObjectPicklistFields(objectName);
    }

    @AuraEnabled
    public static Map<String,String> fetchObjectUserFields(String objectName) {
        return RuleEditorHelper.getObjectUserFields(objectName);
    }

    @AuraEnabled
    public static Map<String,String> fetchPicklistValues(String objectName, String fieldName) {
        return RuleEditorHelper.getPickListValues(objectName, fieldName);
    }

    @AuraEnabled
    public static List<String> fetchTypeOfRuleValues() {
        Map<String, String> mapValues = RuleEditorHelper.getPickListValues('Ludus_Rule__c', 'Type_of_Rule__c');
        return mapValues.values();
    }

    @AuraEnabled
    public static List<String> fetchOperatorValues() {
        Map<String, String> mapValues = RuleEditorHelper.getPickListValues('Ludus_Rule__c', 'Operator__c');
        return mapValues.values();
    }

    @AuraEnabled
    public static void saveSingleRule(Ludus_Rule__c rule) {
        RuleEditorHelper.createRule(rule);
    }

    @AuraEnabled
    public static List<RuleEditorHelper.RuleEditorListItem> fetchAllRules() {
        return RuleEditorHelper.translateRulesToUI(RuleEditorHelper.getAllRules());
    }

}